services:
  backend:
    build:
      context: ./shopper-backend
    ports:
      - "8080:8080"
    volumes:
      - ./shopper-backend:/app
      - /app/node_modules
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shopper_db
    stdin_open: true
    tty: true
    depends_on:
      - db

  frontend:
    build:
      context: ./shopper-frontend
    ports:
      - "80:3000"
    volumes:
      - ./shopper-frontend:/app
      - /app/node_modules
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopper_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
